<a href="https://colab.research.google.com/github/Sauvik27/RockPaperScissor/blob/master/NumPy_Tutorial_for_DS_%26_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
myarr = np.array([[3,6,32,7]])

In [3]:
myarr[0,1]

6

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

In [0]:
myarr[0,1]=45

In [7]:
myarr

array([[ 3, 45, 32,  7]])

**Array Creation**

**Conversion from other Python structures**

In [0]:
listarray=np.array([[1,2,3],[5,8,5],[8,9,3]])

In [9]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [8, 9, 3]])

In [10]:
listarray.dtype

dtype('int64')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
np.array({34,23,43})

array({34, 43, 23}, dtype=object)

**Intrinsic numpy array creation(eg. arange,ones,zeros,etc)**

"zeros" will make an array of (2,5) where each element value is 0

In [0]:
zeros=np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
zeros.size

10

"arange" function will make a numpy array from range 0 to (n-1)

In [0]:
rng=np.arange(12)

In [18]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
rng.shape

(12,)

"linspace" will do equal spacing, in beloww example it will give equal spacing b/w 1 to 50 and 10 is how many numbers we want

In [0]:
linspace = np.linspace(1,50,10)

In [21]:
linspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

"empty" will give an empty array which will give elements having random numbers

In [0]:
emp=np.empty((4,6))

In [23]:
emp

array([[1.69483014e-316, 1.79952226e-316, 1.95687861e-316,
        0.00000000e+000, 1.79953649e-316, 1.79947957e-316],
       [1.79950091e-316, 0.00000000e+000, 0.00000000e+000,
        1.79949380e-316, 2.70803942e-316, 1.95683829e-316],
       [1.95687149e-316, 0.00000000e+000, 1.95689995e-316,
        1.95685252e-316, 1.79950803e-316, 0.00000000e+000],
       [1.79951514e-316, 0.00000000e+000, 1.95686675e-316,
        1.95688572e-316, 0.00000000e+000, 0.00000000e+000]])

"empty_like(arr)" will make an array which will be same like "arr" 

In [0]:
emp_like=np.empty_like(linspace)

In [25]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

"identity(n)" will make n*n array

In [0]:
id=np.identity(45)

In [27]:
id

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [0]:
arr =np.arange(99)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

important

reshape will reshape the given array.

In [0]:
arr=arr.reshape(3, 33)

In [31]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

ravel will bring back the reshaped array to its original state

In [0]:
arr=arr.ravel()

In [33]:
arr.shape

(99,)

**NumPy Axis tutorial**

In [0]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [0]:
ar=np.array(x)

In [36]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

sum of (1+4+7)=12 & (2+5+1)=8 & (3+6+0)=9,
here axis=0(go right in array)

In [37]:
ar.sum(axis=0)

array([12,  8,  9])

sum of (1+2+3)=6 & (4+5+6)=15 & (7+1+0)=8, here axis=1(go down is array)

In [38]:
ar.sum(axis=1)

array([ 6, 15,  8])

Transpose an array

In [39]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [40]:
ar.flat

gives every item in array

In [41]:
for item in ar.flat:
     print(item)

1
2
3
4
5
6
7
1
0


number of dimensions of ar.

In [42]:
ar.ndim

2

In [43]:
ar.size

9

ar.nbytes will give total bytes consumed by all elements in array "ar"

In [44]:
ar.nbytes

72

In [0]:
one = np.array([1,3,4,634,2])

argmax() is a function gives the index of maximum element.

In [46]:
one.argmax()

3

In [47]:
one.argmin()

0

argsort gives an array of index which shows that how the elements in array "one" should be placed so that it will be in ascending order.

In [48]:
one.argsort()

array([0, 4, 1, 2, 3])

first it will rearrange the array "ar" in 1d array then it will give the max value index

In [49]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [50]:
ar.argmin()

8

In [51]:
ar.argmax()

6

In [52]:
ar.argmax(axis=0)

array([2, 1, 1])

In [53]:
ar.argmax(axis=1)

array([2, 2, 0])

In [54]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [55]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [56]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [0]:
ar2=np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 1, 0]])

**MATRIX OPERATION**

sum

In [58]:
ar+ar2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  2,  0]])

multiply

In [59]:
ar*ar2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  1,  0]])

square root

In [60]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

sum of all elements

In [61]:
ar.sum()

29

In [62]:
ar.min()

0

In [63]:
ar.sum(axis=0)

array([12,  8,  9])

gives tuple of the elements in "ar" which is greater than 5, NOTE that this gives index.

In [64]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [65]:
type(np.where(ar>5))

tuple

np.count_nonzero(ar) gives number of nonzero elements in "ar"

In [66]:
np.count_nonzero(ar)

8

In [70]:
ar

array([[1, 2, 3],
       [4, 5, 0],
       [7, 1, 0]])

In [67]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

how numpy takes less space

In [0]:
ar[1,2]=0

In [69]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

for system and parameter check in python we import sys

In [0]:
import sys

now check how numpy array takes less size than normal python array

this is normal python array

In [0]:
py_ar=[0,4,55,2]

this is  numpy array

In [0]:
np_ar=np.array(py_ar)

now the size of python array

In [75]:
sys.getsizeof(1)*len(py_ar)

112

size of numpy array

In [76]:
np_ar.itemsize*np_ar.size

32

In [77]:
np_ar.tolist()

[0, 4, 55, 2]